<ul id="MenuBar" class="MenuBarHorizontal">
  <li id="routeMenu"><a id="routeButton" class="MenuBarItemSubmenu" href="routes.php"></a></li>
  <li id="driverMenu"><a id="driverButton" href="drivers.php"></a>
  <ul>
      <li><a href="managedrivers.php">Manage Drivers</a></li>
      <li><a href="assigndrivers.php">Assign Drivers</a></li>
  </ul>
  </li>
  <li id="operatorMenu"><a id="operatorButton" class="MenuBarItemSubmenu" href="operators.php"></a>
  <ul><li><a href="manageusers.php">Manage Users</a></li>
      <li><a href="mailinglist.php">Maintain Mailing List</a></li>
      <li><a href="callin.php">Schedule Call-In</a></li>
      <li><a href="managecalls.php">Manage Calls</a></li>
      <li><a href="addcustomer.php">Add Customer</a></li>
      <li><a href="routeresults.php">Route Results</a></li>
  </ul>
  </li>
  <li id="reportMenu"><a id="reportButton" href="routehistory.php"></a></li>
  <li id="gpsMenu"><a id="gpsButton" href=""></a></li>
</ul>